version: "3.9"

services:
  app:
    build: .
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repro
    ports:
      - 5432:5432
